services:
    clickhouse:
        image: "clickhouse/clickhouse-server:latest"
        container_name: "clickhouse"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "clickhouse-client", "-q", "SELECT 1"]
            interval: 5s
        volumes:
            - "spryker_b2b_clickhouse:/var/lib/clickhouse"
            - "./.clickhouse/logs:/var/log/clickhouse-server"
            - "./.clickhouse/config/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro"
        ports:
            - "9000:9000"
            - "8123:8123"
        networks:
            - private
        ulimits:
            nofile:
                soft: 262144
                hard: 262144

    ingest:
        image: "node:20-alpine3.20"
        container_name: "clickhouse-ingest"
        restart: unless-stopped
        working_dir: /home/node/app
        env_file:
            - "./.clickhouse/.env.clickhouse"
        environment:
            - NODE_ENV=production
        volumes:
            - ./.clickhouse/ingest:/home/node/app
        ports:
            - "8888:8888"
        command: "npm start"
        networks:
            - private


networks:
    private:

volumes:
    spryker_b2b_clickhouse:
        driver: local
