services:
    clickhouse:
        image: "clickhouse/clickhouse-server:latest"
        container_name: "clickhouse"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "clickhouse-client", "-q", "SELECT 1"]
            interval: 5s
        volumes:
            - "spryker_b2b_clickhouse:/var/lib/clickhouse"
            - "./clickhouse/logs:/var/log/clickhouse-server"
        ports:
            - "9000:9000"
            - "8443:8443"
            - "8123:8123"
        networks:
            - private

networks:
    private:

volumes:
    spryker_b2b_clickhouse:
        driver: local
