services:
    clickhouse-ingest:
        image: "node:20-alpine3.20"
        container_name: "clickhouse-ingest"
        working_dir: /home/node/app
        environment:
            - CLICKHOUSE_HOST=clickhouse
            - CLICKHOUSE_PORT=9000
            - CLICKHOUSE_USER=default
            - CLICKHOUSE_PASSWORD=
            - NODE_ENV=production
        volumes:
            - ./ingest:/home/node/app
        ports:
            - "8125:8125"
        command: "npm start"
        networks:
            - private


networks:
    private:

volumes:
    spryker_b2b_clickhouse_ingest:
        driver: local
